VULN_DB = {
    "headersXContentType": {
        "plugin": {"id": 1001, "name": "Missing X-Content-Type-Options", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 3.1,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 693,
            "name": "Missing X-Content-Type-Options",
            "description": "The X-Content-Type-Options header is missing, which may allow MIME sniffing.",
            "recommendation": "Add X-Content-Type-Options: nosniff to all responses.",
            "severity": "LOW",
            "vid": 1001,
        },
    },
    "headersContentSecurityPolicy": {
        "plugin": {"id": 1002, "name": "Missing Content-Security-Policy", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 4.3,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
            "cwe": 693,
            "name": "Missing Content-Security-Policy",
            "description": "Content-Security-Policy header is missing, increasing the risk of XSS.",
            "recommendation": "Define and enforce a restrictive Content-Security-Policy.",
            "severity": "MEDIUM",
            "vid": 1002,
        },
    },
    "headersStrictTransportSecurity": {
        "plugin": {"id": 1003, "name": "Missing Strict-Transport-Security", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 3.7,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 319,
            "name": "Missing Strict-Transport-Security",
            "description": "HSTS is missing, which may allow protocol downgrade attacks.",
            "recommendation": "Add Strict-Transport-Security with a long max-age.",
            "severity": "LOW",
            "vid": 1003,
        },
    },
    "clickjacking": {
        "plugin": {"id": 1004, "name": "Missing X-Frame-Options", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 4.3,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
            "cwe": 1021,
            "name": "Clickjacking Protection Missing",
            "description": "X-Frame-Options is missing, allowing clickjacking risks.",
            "recommendation": "Add X-Frame-Options: DENY or SAMEORIGIN.",
            "severity": "MEDIUM",
            "vid": 1004,
        },
    },
    "headerReferrerPolicy": {
        "plugin": {"id": 1005, "name": "Missing Referrer-Policy", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 2.6,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 200,
            "name": "Missing Referrer-Policy",
            "description": "Referrer-Policy is missing and may leak sensitive URLs.",
            "recommendation": "Add Referrer-Policy header with a safe policy.",
            "severity": "LOW",
            "vid": 1005,
        },
    },
    "headerPermissionsPolicy": {
        "plugin": {"id": 1006, "name": "Missing Permissions-Policy", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 2.6,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 200,
            "name": "Missing Permissions-Policy",
            "description": "Permissions-Policy is missing, allowing unintended browser features.",
            "recommendation": "Define Permissions-Policy to restrict sensitive APIs.",
            "severity": "LOW",
            "vid": 1006,
        },
    },
    "xXssProtection": {
        "plugin": {"id": 1007, "name": "Missing X-XSS-Protection", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 2.6,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 79,
            "name": "Missing X-XSS-Protection",
            "description": "X-XSS-Protection header is missing.",
            "recommendation": "Add X-XSS-Protection: 1; mode=block where supported.",
            "severity": "LOW",
            "vid": 1007,
        },
    },
    "lackingRedirectHttpHttps": {
        "plugin": {"id": 1008, "name": "HTTP to HTTPS Redirect Missing", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 5.3,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "cwe": 319,
            "name": "HTTP to HTTPS Redirect Missing",
            "description": "HTTP does not redirect to HTTPS or redirects incorrectly.",
            "recommendation": "Force HTTP to HTTPS redirection at the edge or app level.",
            "severity": "MEDIUM",
            "vid": 1008,
        },
    },
    "wildcardTLSCertificate": {
        "plugin": {"id": 1009, "name": "Wildcard TLS Certificate", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 3.1,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 295,
            "name": "Wildcard TLS Certificate Detected",
            "description": "Wildcard certificates can expand attack surface if mishandled.",
            "recommendation": "Limit wildcard usage or ensure strict certificate management.",
            "severity": "LOW",
            "vid": 1009,
        },
    },
    "httpsCertificateVersion": {
        "plugin": {"id": 1010, "name": "Weak TLS Version", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 5.9,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
            "cwe": 326,
            "name": "Weak TLS Version",
            "description": "TLS version is below 1.2.",
            "recommendation": "Disable legacy TLS and enforce TLS 1.2+.",
            "severity": "MEDIUM",
            "vid": 1010,
        },
    },
    "serverDetails": {
        "plugin": {"id": 1011, "name": "Server Information Disclosure", "is_invasive": False, "isRecon": True},
        "vulnerability": {
            "cvss_score": 2.6,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 200,
            "name": "Server Information Disclosure",
            "description": "Server version headers are exposed.",
            "recommendation": "Remove or minimize Server and X-Powered-By headers.",
            "severity": "INFO",
            "vid": 1011,
        },
    },
    "cacheHttpsResponse": {
        "plugin": {"id": 1012, "name": "Cache-Control Missing", "is_invasive": False, "isRecon": False},
        "vulnerability": {
            "cvss_score": 3.7,
            "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
            "cwe": 525,
            "name": "Cache-Control Missing",
            "description": "Cache-control headers are missing on HTTPS responses.",
            "recommendation": "Set Cache-Control and Pragma appropriately for sensitive content.",
            "severity": "LOW",
            "vid": 1012,
        },
    },
}
