"""
Generate a Bitbucket Cloud PR comment with scan results summary.

Mirrors cli/output/pr_comment.py for Bitbucket Pipelines. The markdown
body is generated by `build_comment_body` from the GitHub module so all
platforms render the same content.

Required environment (set automatically by Bitbucket Pipelines):
  - BITBUCKET_REPO_FULL_NAME   e.g. workspace/repo-slug
  - BITBUCKET_PR_ID            (only set on `pull-requests:` pipelines)

Required secret (user-provided, one of):
  - BITBUCKET_TOKEN            repository/workspace access token
                               (sent as Bearer)
  - BITBUCKET_USERNAME + BITBUCKET_APP_PASSWORD
                               (sent as HTTP Basic)
"""
from __future__ import annotations

import base64
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict

from cli.output.pr_comment import build_comment_body


def post_pr_comment(
    report: Dict[str, Any],
    gate: Dict[str, Any],
) -> bool:
    """Post a scan summary comment on the current Bitbucket PR.

    Returns True if the comment was posted successfully.
    """
    repo_full = os.environ.get("BITBUCKET_REPO_FULL_NAME")
    pr_id = os.environ.get("BITBUCKET_PR_ID")

    if not repo_full:
        print(
            "[secoraa] Skipping PR comment: BITBUCKET_REPO_FULL_NAME not set",
            file=sys.stderr,
        )
        return False

    if not pr_id:
        print(
            "[secoraa] Skipping PR comment: not a pull-request pipeline",
            file=sys.stderr,
        )
        return False

    auth_header = _build_auth_header()
    if not auth_header:
        print(
            "[secoraa] Skipping PR comment: no Bitbucket credentials "
            "(set BITBUCKET_TOKEN, or BITBUCKET_USERNAME + BITBUCKET_APP_PASSWORD)",
            file=sys.stderr,
        )
        return False

    body_md = build_comment_body(report, gate)

    workspace_repo = urllib.parse.quote(repo_full, safe="/")
    url = (
        f"https://api.bitbucket.org/2.0/repositories/{workspace_repo}"
        f"/pullrequests/{pr_id}/comments"
    )
    data = json.dumps({"content": {"raw": body_md}}).encode("utf-8")

    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Accept": "application/json",
            "Authorization": auth_header,
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            comment_id = result.get("id", "")
            print(
                f"[secoraa] PR comment posted (id={comment_id})",
                file=sys.stderr,
            )
            return True
    except urllib.error.HTTPError as exc:
        err_body = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
        print(
            f"[secoraa] Failed to post PR comment (HTTP {exc.code}): {err_body[:200]}",
            file=sys.stderr,
        )
    except Exception as exc:
        print(f"[secoraa] Failed to post PR comment: {exc}", file=sys.stderr)

    return False


def _build_auth_header() -> str:
    token = os.environ.get("BITBUCKET_TOKEN")
    if token:
        return f"Bearer {token}"

    username = os.environ.get("BITBUCKET_USERNAME")
    app_password = os.environ.get("BITBUCKET_APP_PASSWORD")
    if username and app_password:
        creds = f"{username}:{app_password}".encode("utf-8")
        return "Basic " + base64.b64encode(creds).decode("ascii")

    return ""
