"""
Generate a GitLab MR comment with scan results summary.

Mirrors cli/output/pr_comment.py for GitLab CI. The markdown body is
generated by `build_comment_body` from the GitHub module so both
platforms render identical content.

Required environment (set automatically by GitLab CI):
  - CI_API_V4_URL          e.g. https://gitlab.com/api/v4
  - CI_PROJECT_ID
  - CI_MERGE_REQUEST_IID   (only set on merge_request_event pipelines)

Required secret (user-provided):
  - GITLAB_TOKEN           project/group access token with `api` scope,
                           or a CI_JOB_TOKEN if the project allows it.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict

from cli.output.pr_comment import build_comment_body


def post_mr_comment(
    report: Dict[str, Any],
    gate: Dict[str, Any],
) -> bool:
    """Post a scan summary comment on the current GitLab MR.

    Returns True if the comment was posted successfully.
    """
    api_url = os.environ.get("CI_API_V4_URL")
    project_id = os.environ.get("CI_PROJECT_ID")
    mr_iid = os.environ.get("CI_MERGE_REQUEST_IID")
    token = os.environ.get("GITLAB_TOKEN") or os.environ.get("CI_JOB_TOKEN")

    if not api_url or not project_id:
        print(
            "[secoraa] Skipping MR comment: CI_API_V4_URL or CI_PROJECT_ID not set",
            file=sys.stderr,
        )
        return False

    if not mr_iid:
        print(
            "[secoraa] Skipping MR comment: not a merge_request_event pipeline",
            file=sys.stderr,
        )
        return False

    if not token:
        print(
            "[secoraa] Skipping MR comment: GITLAB_TOKEN (or CI_JOB_TOKEN) not set",
            file=sys.stderr,
        )
        return False

    body = build_comment_body(report, gate)

    project_id_enc = urllib.parse.quote(str(project_id), safe="")
    url = (
        f"{api_url.rstrip('/')}/projects/{project_id_enc}"
        f"/merge_requests/{mr_iid}/notes"
    )
    data = json.dumps({"body": body}).encode("utf-8")

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    if os.environ.get("GITLAB_TOKEN"):
        headers["PRIVATE-TOKEN"] = token
    else:
        headers["JOB-TOKEN"] = token

    req = urllib.request.Request(url, data=data, headers=headers, method="POST")

    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            note_id = result.get("id", "")
            print(
                f"[secoraa] MR comment posted (note id={note_id})",
                file=sys.stderr,
            )
            return True
    except urllib.error.HTTPError as exc:
        err_body = exc.read().decode("utf-8", errors="replace") if exc.fp else ""
        print(
            f"[secoraa] Failed to post MR comment (HTTP {exc.code}): {err_body[:200]}",
            file=sys.stderr,
        )
    except Exception as exc:
        print(f"[secoraa] Failed to post MR comment: {exc}", file=sys.stderr)

    return False
